/**
 * Action types
 */

export const PROMISE = 'PROMISE';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_USERS = 'FETCH_USERS';
export const LOAD_USERS = 'LOAD_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS ='UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE ='UPDATE_USER_FAILURE';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
